2023-12-07 16:37:49,388 INFO: Potterylog startup [in /Users/dorritochan/Documents/IT_dojo/POTTERY/potterylog/backend/app/__init__.py:44]
2023-12-07 16:49:00,261 ERROR: Exception on /api/pots [GET] [in /Users/dorritochan/Documents/IT_dojo/POTTERY/potterylog/backend/venv/lib/python3.9/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/Users/dorritochan/Documents/IT_dojo/POTTERY/potterylog/backend/venv/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dorritochan/Documents/IT_dojo/POTTERY/potterylog/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dorritochan/Documents/IT_dojo/POTTERY/potterylog/backend/venv/lib/python3.9/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/dorritochan/Documents/IT_dojo/POTTERY/potterylog/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dorritochan/Documents/IT_dojo/POTTERY/potterylog/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/dorritochan/Documents/IT_dojo/POTTERY/potterylog/backend/app/controller.py", line 53, in get_pots
    pots_schema = PotSchema(many=True, only=('id', 'primary_image', 'throw_date', 'vessel_type', 'clay_type', 'used_glazes'))
  File "/Users/dorritochan/Documents/IT_dojo/POTTERY/potterylog/backend/venv/lib/python3.9/site-packages/marshmallow_sqlalchemy/load_instance_mixin.py", line 45, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/dorritochan/Documents/IT_dojo/POTTERY/potterylog/backend/venv/lib/python3.9/site-packages/marshmallow/schema.py", line 400, in __init__
    self._init_fields()
  File "/Users/dorritochan/Documents/IT_dojo/POTTERY/potterylog/backend/venv/lib/python3.9/site-packages/marshmallow/schema.py", line 979, in _init_fields
    raise ValueError(message)
ValueError: Invalid fields for <PotSchema(many=True)>: OrderedSet(['used_glazes']).
2023-12-07 17:45:13,671 INFO: Potterylog startup [in /Users/dorritochan/Documents/IT_dojo/POTTERY/potterylog/backend/app/__init__.py:44]
2023-12-07 17:45:28,843 INFO: Potterylog startup [in /Users/dorritochan/Documents/IT_dojo/POTTERY/potterylog/backend/app/__init__.py:44]
2023-12-07 17:55:04,852 INFO: Potterylog startup [in /Users/dorritochan/Documents/IT_dojo/POTTERY/potterylog/backend/app/__init__.py:44]
2023-12-07 17:55:10,643 ERROR: Exception on /api/pots [GET] [in /Users/dorritochan/Documents/IT_dojo/POTTERY/potterylog/backend/venv/lib/python3.9/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/Users/dorritochan/Documents/IT_dojo/POTTERY/potterylog/backend/venv/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dorritochan/Documents/IT_dojo/POTTERY/potterylog/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dorritochan/Documents/IT_dojo/POTTERY/potterylog/backend/venv/lib/python3.9/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/dorritochan/Documents/IT_dojo/POTTERY/potterylog/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dorritochan/Documents/IT_dojo/POTTERY/potterylog/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/dorritochan/Documents/IT_dojo/POTTERY/potterylog/backend/app/controller.py", line 53, in get_pots
    pots_schema = PotSchema(many=True, only=('id', 'primary_image', 'throw_date', 'vessel_type', 'clay_type', 'used_glazes'))
  File "/Users/dorritochan/Documents/IT_dojo/POTTERY/potterylog/backend/venv/lib/python3.9/site-packages/marshmallow_sqlalchemy/load_instance_mixin.py", line 45, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/dorritochan/Documents/IT_dojo/POTTERY/potterylog/backend/venv/lib/python3.9/site-packages/marshmallow/schema.py", line 400, in __init__
    self._init_fields()
  File "/Users/dorritochan/Documents/IT_dojo/POTTERY/potterylog/backend/venv/lib/python3.9/site-packages/marshmallow/schema.py", line 979, in _init_fields
    raise ValueError(message)
ValueError: Invalid fields for <PotSchema(many=True)>: OrderedSet(['used_glazes']).
2023-12-07 17:55:45,636 INFO: Potterylog startup [in /Users/dorritochan/Documents/IT_dojo/POTTERY/potterylog/backend/app/__init__.py:44]
2023-12-07 17:55:47,916 ERROR: Exception on /api/pots [GET] [in /Users/dorritochan/Documents/IT_dojo/POTTERY/potterylog/backend/venv/lib/python3.9/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/Users/dorritochan/Documents/IT_dojo/POTTERY/potterylog/backend/venv/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dorritochan/Documents/IT_dojo/POTTERY/potterylog/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dorritochan/Documents/IT_dojo/POTTERY/potterylog/backend/venv/lib/python3.9/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/dorritochan/Documents/IT_dojo/POTTERY/potterylog/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dorritochan/Documents/IT_dojo/POTTERY/potterylog/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/dorritochan/Documents/IT_dojo/POTTERY/potterylog/backend/app/controller.py", line 53, in get_pots
    pots_schema = PotSchema(many=True, only=('id', 'primary_image', 'throw_date', 'vessel_type', 'clay_type', 'used_glazes'))
  File "/Users/dorritochan/Documents/IT_dojo/POTTERY/potterylog/backend/venv/lib/python3.9/site-packages/marshmallow_sqlalchemy/load_instance_mixin.py", line 45, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/dorritochan/Documents/IT_dojo/POTTERY/potterylog/backend/venv/lib/python3.9/site-packages/marshmallow/schema.py", line 400, in __init__
    self._init_fields()
  File "/Users/dorritochan/Documents/IT_dojo/POTTERY/potterylog/backend/venv/lib/python3.9/site-packages/marshmallow/schema.py", line 979, in _init_fields
    raise ValueError(message)
ValueError: Invalid fields for <PotSchema(many=True)>: OrderedSet(['used_glazes']).
2023-12-07 17:56:12,567 INFO: Potterylog startup [in /Users/dorritochan/Documents/IT_dojo/POTTERY/potterylog/backend/app/__init__.py:44]
2023-12-07 18:00:32,639 INFO: Potterylog startup [in /Users/dorritochan/Documents/IT_dojo/POTTERY/potterylog/backend/app/__init__.py:44]
2023-12-07 19:13:31,859 INFO: Potterylog startup [in /Users/dorritochan/Documents/IT_dojo/POTTERY/potterylog/backend/app/__init__.py:44]
2023-12-07 19:15:29,778 INFO: Potterylog startup [in /Users/dorritochan/Documents/IT_dojo/POTTERY/potterylog/backend/app/__init__.py:44]
2023-12-11 12:07:25,804 INFO: Potterylog startup [in /Users/dorritochan/Documents/IT_dojo/POTTERY/potterylog/backend/app/__init__.py:44]
2023-12-11 12:08:17,203 INFO: Potterylog startup [in /Users/dorritochan/Documents/IT_dojo/POTTERY/potterylog/backend/app/__init__.py:44]
2023-12-11 12:17:53,832 INFO: Potterylog startup [in /Users/dorritochan/Documents/IT_dojo/POTTERY/potterylog/backend/app/__init__.py:44]
2023-12-11 12:32:50,650 INFO: Potterylog startup [in /Users/dorritochan/Documents/IT_dojo/POTTERY/potterylog/backend/app/__init__.py:44]
2023-12-11 12:33:17,000 INFO: Potterylog startup [in /Users/dorritochan/Documents/IT_dojo/POTTERY/potterylog/backend/app/__init__.py:44]
2023-12-11 16:15:16,068 INFO: Potterylog startup [in /Users/dorritochan/Documents/IT_dojo/POTTERY/potterylog/backend/app/__init__.py:44]
2024-05-23 21:23:19,788 INFO: Potterylog startup [in /Users/dorritochan/Documents/IT_dojo/POTTERY/potterylog/app/__init__.py:41]
2024-05-23 21:23:36,719 INFO: Potterylog startup [in /Users/dorritochan/Documents/IT_dojo/POTTERY/potterylog/app/__init__.py:41]
